server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ead-course-v2
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  rabbitmq:
    addresses: amqps://rdhphlht:rgmyla9SjLQYRTRAoK8ImLsLnAuAiGnu@beaver.rmq.cloudamqp.com/rdhphlht
  output:
    ansi:
      enabled: always

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost