server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: course
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true
  output:
    ansi:
      enabled: always